version: '3'
services:
  spring_app:
    build: untitled
    ports:
      - "8082:8082"
    depends_on:
      - db-dev_home
  db-dev_home:
    image: postgres:12
    restart: always
    container_name: database2
    ports:
      - "54321:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: db-dev
      PGDATA: /home/nikita/IdeaProjects/untitled/data
      POSTGRES_INITDB_DATA: "-A md5"

