version: '3'
services:
  spring_app:
    build: .
    ports:
      - "8082:8082"
    depends_on:
      - db-dev_home
    links:
      - db-dev_home
    restart: always
  db-dev_home:
    image: postgres:12
    restart: always
    container_name: postgresss
    ports:
      - "54321:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: db-dev
      PGDATA: /home/nikita/IdeaProjects/WebSockets
      POSTGRES_INITDB_DATA: "-A md5"

